config/routes.rb
TEDxPerth::Application.routes.draw do

  namespace :admin do
    root :to => 'dashboard#index'
    resources :users
    resources :pages
    resources :events
    resources :posts
    resources :venues
    resources :banner_items, :path => 'banner-items'
  end

  resources :user_session, :path => 'user-sessions'

  resources :password_resets, :path => 'password-resets'

  get   'sign-in',  :to => 'user_sessions#new', :as => :sign_in
  post  'sign-in',  :to => 'user_sessions#create'
  match 'sign-out', :to => 'user_sessions#destroy', :as => :sign_out

  resources :users do
    collection do
      get :welcome
    end
    member do
      post :add_rxp_auth
    end
  end

  resources :events, :only => [:index, :show] do
    member do
      post :withdraw
      post :attending
    end
  end
  
  resources :posts, :only => [:index, :show]
  
  resources :venues, :only => [:show]

  get 'contact-us',  :to => 'contacts#new', :as => :contact_us
  post 'contact-us', :to => 'contacts#create'

  match 'search', :to => 'search#search'

  root :to => 'pages#index'
  
  get '/:id', :to => "pages#show", :as => :page

end

app/models/user.rb
class User < ActiveRecord::Base
  
  def self.for_select
    all.map { |u| [u.to_s, u.id] }
  end
  
  attr_accessible :login, :password, :password_confirmation, :email, :display_name, :mailing_list_ids, :origin
  
  has_many :user_roles, :dependent => :destroy
  has_many :roles, :through => :user_roles
  
  is_sluggable :name

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
    c.validate_email_field  true
    c.account_merge_enabled true
    c.account_mapping_mode  :internal
  end
  
  def to_s
    display_name.present? ? display_name : login
  end
  alias name to_s
  
  def name_changed?
    display_name_changed? || login_changed?
  end
  
  def name_was
    if display_name_changed?
      display_name_was
    elsif display_name.blank? && login_changed?
      login_was
    else
      name
    end
  end
  
  def admin?
    has_role? :admin
  end
  
  def can?(action, object)
    return true if admin?
    method_name = :"#{action}able_by?"
    object.respond_to?(method_name) && object.send(method_name, self)
  end

  def editable_by?(u)
    u == self
  end

  def destroyable_by?(u)
    u == self
  end
  
  # Mailing Lists Tools
  
  # def mailing_lists
  #   @mailing_lists ||= MailingLists.new(self)
  # end
  # 
  # def mailing_list_ids
  #   mailing_lists.ids
  # end
  # 
  # def mailing_list_ids=(value)
  #   mailing_lists.ids = value
  # end
  
  # Role Methods
  
  def self.with_role(name, obj = nil)
    includes(:roles).merge(Role.for(name, obj))
  end
  
  # Give the user this role.
  def has_role!(name, obj = nil)
    self.roles << Role[name, obj] unless has_role?(name, obj)
    true
  end

  # Check if the given user has this role
  def has_role?(name, obj = nil)
    roles.for(name, obj).exists?
  end

  # Remove a role from this user
  def remove_role!(name, obj = nil)
    roles.delete(Role[name, obj]) if has_role?(name, obj)
    true
  end
  
  def attending?(event)
    event && event.attending?(self)
  end
  
  def attending!(event)
    event && event.attending!(event)
  end
  
  def withdraw!(event)
    event && event.withdraw!(event)
  end
  
  def events
    Event.includes(:roles => :user_roles).where(:user_roles => {:user_id => self.id})
  end
  
  def completed_events
    events.where(:state => %w(published completed)).where('ends_at <= ?', Time.now)
  end
  
end

# == Schema Information
#
# Table name: users
#
#  id                :integer(4)      not null, primary key
#  login             :string(255)
#  crypted_password  :string(255)
#  password_salt     :string(255)
#  persistence_token :string(255)
#  email             :string(255)
#  login_count       :integer(4)
#  last_request_at   :datetime
#  last_login_at     :datetime
#  current_login_at  :datetime
#  last_login_ip     :string(255)
#  current_login_ip  :string(255)
#  display_name      :string(255)
#  origin            :string(255)
#  perishable_token  :string(255)     not null
#  cached_slug       :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  use_controller_exts :slugged_resource
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :require_user, :only   => [:edit, :destroy, :update, :welcome]
  before_filter :prepare_user, :except => [:new, :create, :index, :welcome]
  before_filter :check_authz,  :only   => [:edit, :destroy, :update]
  
  hide_sidebar! :only => [:new, :edit, :create, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_back_or_default welcome_users_path, :notice => tf('signup.thanks')
    else
      render :action => 'new'
    end
  end

  def edit
    flash[:profile_notice] = tf('profile.full_incomplete')
    @user.valid?
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_back_or_default user_path(@user), :notice => tf('account.updated')
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, :notice => tf('account.destroyed')
  end

  def add_rxp_auth
    if @user.save
      flash[:notice] = tf('account.added_rpx_auth')
      redirect_to user_path(@user)
    else
      render :action => 'edit'
    end
  end

  def welcome
  end

  protected

  def check_authz
    verb = (params[:action] == "destroy" ? :destroy  : :edit)
    unauthorized! tf('account.different_user') unless can?(verb, @user)
  end

  def prepare_user
    @user = params[:id] == "current" ? current_user : User.find_using_slug!(params[:id])
    return redirect_to :users, :alert => tf('account.unknown_user') unless @user.present?
    add_title_variables! :user => @user.to_s
  end

end

app/views/users/_form.html.haml
- if flash[:profile_notice].present?
  %p#profile-notice= flash[:profile_notice]

= semantic_form_for @user do |form|
  
  = form.inputs :name => "Tell us about yourself" do
    = form.input :login, :hint => "Choose something you'll remember and don't mind other people seeing.", :required => @user.new_record?, :label => "Your Login"
    = form.input :email, :hint => "We promise we wont misbehave with your email address.", :required => @user.new_record?, :label => "Your Email"
    - if @user.new_record? || @user.rpx_identifiers.blank?
      = form.input :password, :required => @user.new_record?, :label => "Your Password"
      = form.input :password_confirmation, :label => "Confirm your Password"
    = form.input :display_name, :hint => "You don't have to fill it in but if you do, other users will see this instead of your login."
    
  = form.buttons do
    = form.commit_button_with_cancel(@user.new_record? ? {:cancel => {:url => :new_user, :text => "Change Account Type", :id => "auth-selector-link"}} : {})

app/views/users/edit.html.haml
= render :partial => 'form'

app/views/users/new.html.haml
- on_new_page = controller.action_name == "new" && !params[:traditional]

#authentication-container

  - if on_new_page
    - has_jammit_js :authentication_with_rpx_now
    %dl#authentication-choices
      %dt Sign up using...
      %dd.choice= rpxnow_link tu('authentication.external'), sign_in_url, :id => 'rpxnow-authentication-link'
      %dd.or or
      %dd.choice= link_to tu('authentication.internal'), new_user_path(:traditional => true), :id => 'traditional-authentication-link'
  
  #authentication-with-standard-account{:style => ("display: none;" if on_new_page)}
    %h1 We'd love to know more about you...
    %p.summary
      Before you can continue on, we need to know a couple of small details.
      Once that's done, you'll be able to continue on from where you were before.
    = partial :form

app/views/users/show.html.haml
- if can?(:edit, @user)
  %p#edit-profile
    Hey, it looks like this may be your profile!
    = link_to "Click here", edit_user_path(params[:id])
    to edit your details.
    
%h3 Events Attended
- events = @user.completed_events.all
%ul#events-attended
  - if events.empty?
    %li.no-attended-events We are yet to record this users attendance to an event.
  - events.each do |event|
    %li.attended-event
      Attended
      = link_to event.name, event
      at
      = pretty_time event.starts_at

- if logged_in? && current_user.admin?
  %p#holy-crap-an-admin
    = link_to 'Click here', :admin_root
    to visit the admin area.

app/views/users/welcome.html.haml
%p#general-page-notice
  Thanks! You're now a member!
  Next, you'll likely want to check out one of the links below:

%h3 Get Started
%ul#getting-started
  %li= link_to 'View your profile', user_path(:current), :id => 'your-profile-item'