config/routes.rb
TEDxPerth::Application.routes.draw do

  namespace :admin do
    root :to => 'dashboard#index'
    resources :users
    resources :pages
    resources :events
    resources :posts
    resources :venues
    resources :banner_items, :path => 'banner-items'
  end

  resources :user_session, :path => 'user-sessions'

  resources :password_resets, :path => 'password-resets'

  get   'sign-in',  :to => 'user_sessions#new', :as => :sign_in
  post  'sign-in',  :to => 'user_sessions#create'
  match 'sign-out', :to => 'user_sessions#destroy', :as => :sign_out

  resources :users do
    collection do
      get :welcome
    end
    member do
      post :add_rxp_auth
    end
  end

  resources :events, :only => [:index, :show] do
    member do
      post :withdraw
      post :attending
    end
  end
  
  resources :posts, :only => [:index, :show]
  
  resources :venues, :only => [:show]

  get 'contact-us',  :to => 'contacts#new', :as => :contact_us
  post 'contact-us', :to => 'contacts#create'

  match 'search', :to => 'search#search'

  root :to => 'pages#index'
  
  get '/:id', :to => "pages#show", :as => :page

end

app/views/shared/_auth_nav.html.haml
- if logged_in?
  Signed in as
  %span#current-user= link_to current_user.to_s, user_path(:current), :title => "View your profile"
  = link_to "(sign out)", sign_out_path
- else
  Want the full experience?
  %span.auth-action= link_to "Sign up", :new_user
  or
  %span.auth-action= link_to "Sign in", :sign_in

app/views/shared/_default_sidebar.html.haml
%h2 The Next Event

- next_event = Event.for_sidebar.next
- if next_event.present?
  #next-event
    %p
      The next TEDxPerth event is
      == #{link_to next_event.name, next_event},
      == held #{pretty_date_range next_event.starts_at, next_event.ends_at}.
    %p
      This is
      = distance_of_time_in_words Time.now, next_event.starts_at, false
      away.
- else
  %p#no-next-event
    There is currently no available information
    on the next TEDxPerth event.

%h2 TEDxPerth Tweets

%ul#tweets-listing
  %li.loading Loading tweets...

%h2 Recent Blog Posts

- posts = Post.for_sidebar.all
%ul#posts-listing
  - if posts.empty?
    %li.loading There are currently no published posts on this blog.
  - posts.each do |post|
    %li= link_to post.title, post_path(post)

app/views/shared/_footer.html.haml
%nav= partial 'shared/menu', :expanded => false
%p#copyright-statement
  == &copy; #{copyright 2010}, The TED<sup>x</sup>Perth Team. All rights reserved.
  This independent TEDx event is operated under license from TED.

app/views/shared/_header.html.haml
%h1= link_to "TEDxPerth", :root
%section#inner-header-right
  %nav#authentication= partial 'shared/auth_nav'
  #search= partial 'shared/search'

%nav#page-navigation= partial 'shared/menu', :expanded => true

app/views/shared/_menu.html.haml
%ul
  - Page.for_menu.each do |page|
    = eml page.menu_title, page_path_with_home(page), :expanded => expanded, :title => page.menu_subtitle
  = eml "Events", :events, :expanded => expanded, :title => "Upcoming & Past Events"
  = eml "Our Blog", posts_path, :expanded => expanded, :title => "Find out what's going on"
  = eml "Contact Us", :contact_us, :expanded => expanded, :title => "Let us know what you think!"
  - if !expanded
    = ml "Admin Area", :admin_root

app/views/shared/_search.html.haml
#search
  = form_tag :search, :method => "get" do
    = text_field_tag :query, "", :type => "search", :placeholder => tu("search.placeholder"), :class => "search-box"
    = button_tag "search", :type => "submit"