config/routes.rb
TEDxPerth::Application.routes.draw do

  namespace :admin do
    root :to => 'dashboard#index'
    resources :users
    resources :pages
    resources :events
    resources :posts
    resources :venues
    resources :banner_items, :path => 'banner-items'
  end

  resources :user_session, :path => 'user-sessions'

  resources :password_resets, :path => 'password-resets'

  get   'sign-in',  :to => 'user_sessions#new', :as => :sign_in
  post  'sign-in',  :to => 'user_sessions#create'
  match 'sign-out', :to => 'user_sessions#destroy', :as => :sign_out

  resources :users do
    collection do
      get :welcome
    end
    member do
      post :add_rxp_auth
    end
  end

  resources :events, :only => [:index, :show] do
    member do
      post :withdraw
      post :attending
    end
  end
  
  resources :posts, :only => [:index, :show]
  
  resources :venues, :only => [:show]

  get 'contact-us',  :to => 'contacts#new', :as => :contact_us
  post 'contact-us', :to => 'contacts#create'

  match 'search', :to => 'search#search'

  root :to => 'pages#index'
  
  get '/:id', :to => "pages#show", :as => :page

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend RejectIfHelper
  
  validates_presence_of :name, :starts_at, :ends_at, :description, :notes, :venue, :image
  validate :check_valid_starts_at
  validate :check_valid_ends_at
  
  belongs_to :venue
  
  has_many :roles, :as => :owner
  
  has_many :ted_videos
  
  accepts_nested_attributes_for :ted_videos, :reject_if => reject_if_proc, :allow_destroy => true
  
  mount_uploader :image, EventImageUploader
  
  scope :viewable, where(:state => %w(published completed))
  scope :for_sidebar, select('id, venue_id, name, starts_at, ends_at, cached_slug')
  scope :optimized, includes(:ted_videos, :venue)
  
  acts_as_indexed :fields => [:name, :rendered_description, :rendered_notes], :if => Proc.new { |event| event.published? || event.completed? }
  
  def self.upcoming
    viewable.order('starts_at ASC').where('starts_at >= ?', Time.now)
  end
  
  def self.completed
    viewable.order('ends_at DESC').where('ends_at <= ?', Time.now)
  end
  
  def self.next
    upcoming.first
  end
  
  is_sluggable :name
  
  is_convertable :description, :notes, :validate => false
  validate_convertable_format :description, :notes
  
  state_machine :state, :initial => :pending do
    state :pending
    state :published
    state :completed
    
    event :publish do
      transition :pending => :published
    end
    
    event :complete do
      transition :published => :completed
    end
  end
  
  # Hack hack hack!
  
  def attending
    User.with_role(:attendee, self)
  end
  
  def attending?(user)
    attending.where(:users => {:id => user.id}).exists?
  end
  
  def attending!(user)
    user.has_role! :attendee, self
    increment! :attendee_count
  end
  
  def withdraw!(user)
    user.remove_role! :attendee, self
    decrement! :attendee_count
  end
  
  def state_events_for_select
    state_events.map do |se|
      name = ::I18n.t("#{self.class.model_name.underscore}.#{se}", :default => se.to_s.humanize, :scope => "ui.state_events")
      [name, se]
    end
  end
  
  # Permissions control.
  
  def can_attend?(user)
    can_change_attendance? && !attending?(user)
  end
  
  def can_withdraw?(user)
    can_change_attendance? && attending?(user)
  end
  
  def can_change_attendance?
    published? && starts_at < Time.now
  end
  
  def upcoming?
    (completed? || published?) && starts_at >= Time.now
  end
  
  def completed?
    published? && ends_at <= Time.now
  end
  
  protected
  
  def check_valid_starts_at
    if starts_at.present? && starts_at < Time.now
      errors.add :starts_at, "must be in the future."
    end
  end
  
  def check_valid_ends_at
    if starts_at.present? && ends_at.present? && ends_at <= starts_at
      errors.add :ends_at, "must be after the start of this event."
    end
  end
  
end

# == Schema Information
#
# Table name: events
#
#  id                   :integer(4)      not null, primary key
#  name                 :string(255)
#  starts_at            :datetime
#  ends_at              :datetime
#  description_format   :string(255)
#  description          :text
#  rendered_description :text
#  cached_slug          :string(255)
#  notes_format         :string(255)
#  notes                :text
#  rendered_notes       :text
#  state                :string(255)
#  created_at           :datetime
#  updated_at           :datetime
#  attendee_count       :integer(4)      default(0)
#  venue_id             :integer(4)
#

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  use_controller_exts :slugged_resource
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :require_user,  :only   => [:attending, :withdraw]
  before_filter :prepare_event, :except => [:index]
  
  def index
    @upcoming_events  = Event.upcoming.all
    @completed_events = Event.completed.all
    @events_page      = Page[:events]
  end
  
  def show
    add_title_variables! :event => @event.name
  end
  
  def attending
    if can? :attend, @event
      @event.attending! current_user
      redirect_to @event, :notice => tf('events.attending', :event => @event.name)
    else
      redirect_to @event, :alert => tf('events.unable_to_attend', :event => @event.name)
    end
  end
  
  def withdraw
    if can? :withdraw, @event
      @event.withdraw! current_user
      redirect_to @event, :notice => tf('events.withdrawn', :event => @event.name)
    else
      redirect_to @event, :alert => tf('events.unable_to_withdraw', :event => @event.name)
    end
  end

  protected
  
  def prepare_event
    @event = Event.viewable.optimized.find_using_slug!(params[:id])
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
  
  def linked_event_preview(event)
    html = first_paragraph_of(event.description_as_html)
    link = link_to "View more details &raquo;".html_safe, event
    html.gsub(/(\.|\!|\?)?\s*<\/p>/) { "#{$1 || "."} #{link}</p>" }.html_safe
  end
  
  def style_for_image(image)
    if image.blank?
      nil
    else
      "background-image: url('#{image.url}');"
    end
  end
  
end

app/views/events/_attendance.html.haml
- if @event.upcoming?
  - if logged_in? && @event.attending?(current_user)
    .attending#attendance= inline_button "I can't make it!", withdraw_event_path(@event)
  - elsif logged_in?
    .attend#attendance= inline_button "I plan on attending!", attending_event_path(@event)
  - else
    .attend#attendance= inline_button "I'd like to attend!", attending_event_path(@event)
  
- elsif @event.completed? && logged_in? && @event.attending?(current_user)
  .attended#attendance
    You attended this TEDxPerth event.

app/views/events/_event_listing.html.haml
%li.event
  %h3= link_to event_listing.name, event_listing
  %p.event-metadata
    This event
    = event_listing.upcoming? ? "will be" : "was"
    == run from #{pretty_date_range event_listing.starts_at, event_listing.ends_at}.
      
  = linked_event_preview event_listing

app/views/events/_information.html.haml
%dl#event-information
  %dt.event-venue: Where:
  %dd.event-venue= link_to @event.venue.to_s, @event.venue, :id => "event-venue"
  %dt.event-time When:
  %dd.event-time= pretty_date_range @event.starts_at, @event.ends_at

app/views/events/index.html.haml
%h1 All TEDxPerth Events

= render_page! @events_page if @events_page

%h2 Upcoming Events

%ul.events#upcoming-events
  = render :collection => @upcoming_events, :partial => 'event_listing'
  - if @upcoming_events.empty?
    %li.no-events There are currently no details on upcoming events.
    
%h2 Completed Events

%ul.events#completed-events
  = render :collection => @completed_events, :partial => 'event_listing'
  - if @completed_events.empty?
    %li.no-events There are currently no details on completed events.

app/views/events/show.html.haml
- has_jammit_js :events_page

%article#event
  
  #event-image{:style => style_for_image(@event.image)}
    %h1= page_title
    = partial 'attendance'
    = partial 'information'

  %h2== About #{@event.name}
  %section#event-description= @event.description_as_html
  

  %h2 Event Notes
  %section#event-notes= @event.notes_as_html

  - unless @event.ted_videos.empty?

    %h2 Event Videos

    #video-player-container

    %ul#event-videos
      - if @event.completed?
        - @event.ted_videos.each do |video|
          %li.event-video
            .video-controls
              = link_to video.title, video.url, :class => 'video-title'
              = link_to "show video", '#', :class => 'show-video'
              = link_to "hide video", '#', :class => 'hide-video'
            %p.video-description= video.description
            .video-embed= video.embed_code.html_safe
      - else
        %li.event-not-completed== The videos shown at #{@event.name} will be revealed post-event.
  
    %p.video-copyright-notice
      Videos used under a
      = link_to "Creative Commons by-nc-nd", "http://creativecommons.org/licenses/by-nc-nd/3.0/"
      license from
      == #{link_to "TED.com", "http://ted.com/"}.